package PetroApp

const token string = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXBwLnBldHJvYXBwZWcuY29tL2Rhc2hib2FyZF9hcGkvbG9naW4iLCJpYXQiOjE3NTUxODcyNzYsImV4cCI6MTc1NjM5Njg3NiwibmJmIjoxNzU1MTg3Mjc2LCJqdGkiOiJObHJpYUpCQVdUNkZ3bVZTIiwic3ViIjoiODI0NzUiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.P4Gv3vjwThTRNPq06pCPamMk3dzB1rKJxIV-3BcYBbw"

const cookie string = "laravel_session=cXRwEsvfyVWlqrdJdTyumTXY0wDdt4mFW7br1dCC"

const baseUrl string = "https://app.petroappeg.com/dashboard_api/bills"
