package PetroApp

const token string = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXBwLnBldHJvYXBwZWcuY29tL2Rhc2hib2FyZF9hcGkvbG9naW4iLCJpYXQiOjE3NTYyNDY1MzYsImV4cCI6MTc1NzQ1NjEzNiwibmJmIjoxNzU2MjQ2NTM2LCJqdGkiOiJ3aFFMVFM3V1hHWW16bFZwIiwic3ViIjoiODI0NzUiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.6MRMluHTpOW-WvUtAtofk75fHgNgzJBOB-Ke1Mh9DwI"

const cookie string = "laravel_session=d9YEUjp6DVOqI2dIgwouPCqL0WY9LGM8X5S9yhAG"

const baseUrl string = "https://app.petroappeg.com/dashboard_api"
