name: Build and Deploy Falcon Go App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Ensure HTTPS is enabled
      run: |
        # Check if HTTPS is commented out, if so uncomment it
        if grep -q "// app.ListenTLS" FiberConfig/Routes.go; then
          # Uncomment the HTTPS line
          sed -i 's|// app.ListenTLS(":3001", "/etc/letsencrypt/live/apextransport.ddns.net/fullchain.pem", "/etc/letsencrypt/live/apextransport.ddns.net/privkey.pem")|app.ListenTLS(":3001", "/etc/letsencrypt/live/apextransport.ddns.net/fullchain.pem", "/etc/letsencrypt/live/apextransport.ddns.net/privkey.pem")|g' FiberConfig/Routes.go
          
          # Comment out HTTP if it's uncommented
          sed -i 's|app.Listen(":3001")|// app.Listen(":3001")|g' FiberConfig/Routes.go
          
          echo "Modified code to use HTTPS"
        else
          echo "HTTPS already enabled in the code, no changes needed"
        fi

    - name: Build Go application for Ubuntu
      run: |
        # Build for Linux (Ubuntu)
        GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o main ./main.go
        # Make the binary executable
        chmod +x main

    - name: Prepare deployment package
      run: |
        # Create a directory for all files to deploy
        mkdir -p deployment
        
        # Copy the binary
        cp main deployment/
        
        # Copy all necessary directories for static files
        cp -r Templates static deployment/ || true
        
        # Copy any config files you might need
        cp -r config*.* deployment/ || true
        
        # Create a tarball for easier transfer
        tar -czf deployment.tar.gz -C deployment .

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        # Create a backup script to run on the server
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        # Create directory if it doesn't exist
        sudo mkdir -p /var/www/FalconGo
        
        # Stop the service
        sudo systemctl stop Falcon || true

        # Backup the database
        if [ -f /var/www/FalconGo/database.db ]; then
          echo "Backing up database..."
          cp /var/www/FalconGo/database.db /var/www/FalconGo/database.db.bak
        fi

        # Extract new files (preserving database)
        echo "Extracting new files..."
        cd /var/www/FalconGo
        
        # Extract everything except database.db
        tar -xzf /tmp/deployment.tar.gz --skip-old-files
        
        # Make sure binary is executable
        chmod +x /var/www/FalconGo/main
        
        # Set ownership
        sudo chown -R root:root /var/www/FalconGo
        
        # Make sure directories for static files exist
        mkdir -p /var/www/FalconGo/CarLicenses
        mkdir -p /var/www/FalconGo/CarLicensesBack
        mkdir -p /var/www/FalconGo/CalibrationLicenses
        mkdir -p /var/www/FalconGo/CalibrationLicensesBack
        mkdir -p /var/www/FalconGo/DriverLicenses
        mkdir -p /var/www/FalconGo/SafetyLicenses
        mkdir -p /var/www/FalconGo/DrugTests
        mkdir -p /var/www/FalconGo/CriminalRecords
        mkdir -p /var/www/FalconGo/IDLicenses
        mkdir -p /var/www/FalconGo/IDLicensesBack
        mkdir -p /var/www/FalconGo/TankLicenses
        mkdir -p /var/www/FalconGo/TankLicensesBack
        mkdir -p /var/www/FalconGo/ServiceProofs
        mkdir -p /var/www/FalconGo/static

        # Restart service
        echo "Restarting service..."
        sudo systemctl restart Falcon
        echo "Deployment completed!"
        EOF
        
        chmod +x deploy.sh
        
        # Copy the deployment package to the VPS
        scp -i ~/.ssh/deploy_key -P ${{ secrets.SSH_PORT }} deployment.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/
        
        # Copy and execute the deployment script
        scp -i ~/.ssh/deploy_key -P ${{ secrets.SSH_PORT }} deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/
        ssh -i ~/.ssh/deploy_key -P ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /tmp/deploy.sh"

    - name: Verify deployment
      run: |
        ssh -i ~/.ssh/deploy_key -P ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl status Falcon | grep 'active'" || true